[COMMON]
DataSource = PMXKZALSQ0002
InitialCatalog = PMK_PSS
NetLib = dbmssocn
UID = PSS
PWD = 

[LEIS]
QueueLength = 50
DataBase = 'K:\DEVL\PSS III\EDPS\bin\EDPS_Local.MDB'
LogPath = 'K:\DEVL\PSS III\EDPS\bin\LEIS.LOG'
TryRepeats = 5
; set to 0 to disable priority change. Don't change it without necessary.
; 32 - normal / 64 - low / 128 - high / 256 - realtime
PriorityRun = 0

[QR]
RestartTime = 11:41
LogPath = 'K:\DEVL\PSS III\EDPS\bin\QR.LOG'
KillSent = NO
TimeLoop = 5
; set to 0 to disable priority change. Don't change it without necessary.
; 32 - normal / 64 - low / 128 - high / 256 - realtime
PriorityRun = 0

[DBIS]
LogPath = 'K:\DEVL\PSS III\EDPS\bin\DBI.LOG'
; Parameters' type: 	1 - Direct described parameters
;			2 - Provider described parameters
ParametersType = 1
; Quantity of attepts to make a connection before error message
RepeatQty = 5
; set to 0 to disable priority change. Don't change it without necessary.
; 32 - normal / 64 - low / 128 - high / 256 - realtime
PriorityRun = 0

[SIS]
LogPath = 'K:\DEVL\PSS III\EDPS\bin\'
PriorityRun = 0
EDPSID = 2
WorkThreads = 1
ShowLogForms = 1
; next parameters in ms
SchedulerStep = 1000
CalculatorStep = 10
AFDRStep = 10
