import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\prsht.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtml.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\dimm.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtmhst.idl";
import "c:\program files\microsoft visual studio .net 2003\vc7\platformsdk\include\docobj.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\exdisp.idl";
import "C:\Program Files\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\objsafe.idl";

[
	object,
	uuid(5A1EA625-128E-48A7-A506-9E2824F76798),
	dual,
	helpstring("IEdpsTimer Interface"),
	pointer_default(unique)
] 
#line 14 "c:\\igor\\edps update 2006\\edpsutils\\edpstimer.h"
interface IEdpsTimer : IDispatch {
#line 16 "c:\\igor\\edps update 2006\\edpsutils\\edpstimer.h"
	[propget,id(1),helpstring("Scheduled event is Enabled")] HRESULT  Enabled([out,retval] VARIANT_BOOL *pVal);
	[propput,id(1),helpstring("Scheduled event is Enabled")] HRESULT  Enabled([in] VARIANT_BOOL newVal);
	[propget,id(2),helpstring("Timer Event Interval")] HRESULT  Interval([out,retval] LONG *pVal);
	[propput,id(2),helpstring("Timer Event Interval")] HRESULT  Interval([in] LONG newVal);
	[propget,id(3),helpstring("property HitsCount")] HRESULT  HitsCount([out,retval] LONG *pVal);
};


[ version(1.0), uuid(075EE564-ACA0-4800-9D24-06768C3D84F3), helpstring("Edps Utilites v1.0") ]
library EdpsUtils
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		uuid(B12F0FB5-245A-415A-844E-38B0B6EF6164),
		helpstring("_IEdpsTimerEvents Interface")
	] 
#line 31 "c:\\igor\\edps update 2006\\edpsutils\\edpstimer.h"
	dispinterface _IEdpsTimerEvents {
	properties:

	methods:
		[id(1),helpstring("Method OnTimer called by the timer service for a scheduled event."),source] HRESULT  OnTimer();
	};

	[
		version(1.0),
		uuid(E08597E3-A6D1-4549-BD7C-5EDBAEF3094C),
		helpstring("EdpsTimer Class")
	] 
#line 49 "c:\\igor\\edps update 2006\\edpsutils\\edpstimer.h"
	coclass CEdpsTimer {
		interface IEdpsTimer;
		[default, source]	interface _IEdpsTimerEvents;
	};

}

